import type { SpendingCategory } from "../../src/lib/taxonomy";

export const OSM_TAG_TO_CATEGORY = {
  "amenity=atm": "cash-withdrawal",
  "amenity=bank": "loans-bank-fees",
  "amenity=bar": "restaurants",
  "amenity=bicycle_rental": "transport-travel",
  "amenity=bureau_de_change": "cash-withdrawal",
  "amenity=cafe": "restaurants",
  "amenity=car_rental": "transport-travel",
  "amenity=car_wash": "car-fuel",
  "amenity=charging_station": "car-fuel",
  "amenity=cinema": "entertainment",
  "amenity=clinic": "health",
  "amenity=dentist": "health",
  "amenity=doctors": "health",
  "amenity=driving_school": "family-education",
  "amenity=fast_food": "restaurants",
  "amenity=food_court": "restaurants",
  "amenity=fuel": "car-fuel",
  "amenity=hospital": "health",
  "amenity=ice_cream": "restaurants",
  "amenity=nightclub": "restaurants",
  "amenity=parking": "car-fuel",
  "amenity=pharmacy": "health",
  "amenity=pub": "restaurants",
  "amenity=restaurant": "restaurants",
  "amenity=theatre": "entertainment",
  "leisure=fitness_centre": "entertainment",
  "leisure=sports_centre": "entertainment",
  "man_made=water_works": "bills-utilities",
  "office=energy_supplier": "bills-utilities",
  "office=insurance": "bills-utilities",
  "shop=bag": "shopping",
  "shop=bakery": "groceries",
  "shop=beauty": "health",
  "shop=books": "entertainment",
  "shop=butcher": "groceries",
  "shop=car_parts": "car-fuel",
  "shop=car_repair": "car-fuel",
  "shop=cheese": "groceries",
  "shop=clothes": "shopping",
  "shop=computer": "shopping",
  "shop=convenience": "groceries",
  "shop=cosmetics": "health",
  "shop=deli": "groceries",
  "shop=department_store": "shopping",
  "shop=doityourself": "bills-utilities",
  "shop=electronics": "shopping",
  "shop=florist": "shopping",
  "shop=frozen_food": "groceries",
  "shop=furniture": "shopping",
  "shop=greengrocer": "groceries",
  "shop=hairdresser": "health",
  "shop=hardware": "bills-utilities",
  "shop=hearing_aids": "health",
  "shop=insurance": "bills-utilities",
  "shop=jewelry": "shopping",
  "shop=mobile_phone": "shopping",
  "shop=optician": "health",
  "shop=seafood": "groceries",
  "shop=shoes": "shopping",
  "shop=sports": "entertainment",
  "shop=supermarket": "groceries",
  "shop=toys": "entertainment",
  "shop=variety_store": "shopping",
  "telecom=data_center": "bills-utilities",
  "telecom=exchange": "bills-utilities",
  "telecom=internet_service_provider": "bills-utilities",
  "telecom=service_provider": "bills-utilities",
  "tourism=apartment": "transport-travel",
  "tourism=guest_house": "transport-travel",
  "tourism=hostel": "transport-travel",
  "tourism=hotel": "transport-travel",
  "tourism=motel": "transport-travel",
  "tourism=museum": "entertainment",
  "tourism=theme_park": "entertainment",
} as const satisfies Record<string, SpendingCategory>;

export const mapOsmTagToCategory = (
  tag: string | null
): SpendingCategory | null => {
  if (tag === null) {
    return null;
  }

  // SAFETY: tag is an arbitrary string; the assertion narrows for the const lookup
  return OSM_TAG_TO_CATEGORY[tag as keyof typeof OSM_TAG_TO_CATEGORY] ?? null;
};
