import type { IconComponent, IconName } from "@freenary/ui/lib/icon-context";
import {
  RiAddLine,
  RiArrowDownLine,
  RiArrowDownSLine,
  RiArrowLeftLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowUpLine,
  RiBrainLine,
  RiCalendarLine,
  RiCheckLine,
  RiCloseLine,
  RiComputerLine,
  RiCornerDownLeftLine,
  RiExpandUpDownLine,
  RiFileCopyLine,
  RiImageLine,
  RiLoader4Line,
  RiMenuLine,
  RiMoonLine,
  RiMore2Line,
  RiMoreLine,
  RiPencilLine,
  RiSearchLine,
  RiSidebarFoldLine,
  RiSidebarUnfoldLine,
  RiSunLine,
} from "@remixicon/react";

import { remixIcon } from "@/lib/remix-icon";

export const ffIcons = {
  "arrow-down": remixIcon(RiArrowDownLine),
  "arrow-left": remixIcon(RiArrowLeftLine),
  "arrow-right": remixIcon(RiArrowRightLine),
  "arrow-up": remixIcon(RiArrowUpLine),
  brain: remixIcon(RiBrainLine),
  calendar: remixIcon(RiCalendarLine),
  check: remixIcon(RiCheckLine),
  "chevron-down": remixIcon(RiArrowDownSLine),
  "chevron-right": remixIcon(RiArrowRightSLine),
  "chevrons-up-down": remixIcon(RiExpandUpDownLine),
  copy: remixIcon(RiFileCopyLine),
  "corner-down-left": remixIcon(RiCornerDownLeftLine),
  image: remixIcon(RiImageLine),
  loader: remixIcon(RiLoader4Line),
  menu: remixIcon(RiMenuLine),
  monitor: remixIcon(RiComputerLine),
  moon: remixIcon(RiMoonLine),
  "more-horizontal": remixIcon(RiMoreLine),
  "more-vertical": remixIcon(RiMore2Line),
  "panel-left": remixIcon(RiSidebarFoldLine),
  "panel-right": remixIcon(RiSidebarUnfoldLine),
  pencil: remixIcon(RiPencilLine),
  plus: remixIcon(RiAddLine),
  search: remixIcon(RiSearchLine),
  sun: remixIcon(RiSunLine),
  x: remixIcon(RiCloseLine),
} satisfies Partial<Record<IconName, IconComponent>>;
